language: node_js

node_js:
  - "10"

branches:
  only:
  - master

cache: yarn

before_script:
  - npm install -g codecov

script:
  - yarn run lint
  # - yarn run test --watch=false --code-coverage
  # - yarn run e2e
  - yarn build --prod --aot --progress=false --base-href "/gones-streamer/"

after_success:
  - yarn run deploy
  - yarn run test --watch=false --code-coverage
  - codecov