# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
 pull_request:
  branches: [ master, develop ]
 push:
  branches: [ master, develop, 'feature/**', 'fix/**' ]

jobs:
  test:
    name: Test
    if: "!contains(toJSON(github.event.commits.*.message), 'skip ci')"
    runs-on: windows-latest
    steps:
    # Fetch the latest commit
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Setup Node.js using the appropriate version
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    # Install package dependencies
    - name: Install
      run: yarn install --frozen-lockfile

    # # Run tests
    # - name: Test
    #   run: npm test

    # Run build
    - name: Build
      run: yarn build

  release:
    name: Release
    # Only release on push to master
    if: "github.event_name == 'push' && github.ref == ('refs/heads/develop' || 'refs/heads/master') && !contains(toJSON(github.event.commits.*.message), 'skip ci')"
    runs-on: windows-latest
    # Waits for test jobs for each Node.js version to complete
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Download OBS Binaries
        run: yarn getBinary

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Package Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release